language: python
sudo: false
python:
- '2.7'
- '3.4'
- '3.5'

cache:
  directories:
  - $HOME/.pip-cache/

install:
  - pip install -r requirements-dev.txt
  - pip install coveralls

script:
- flake8
- py.test --cov=junction -v --tb=native junction
- coverage report -m

after_success:
  coveralls

notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]
